theme = "zhxo-red"

[editor]
true-color = true
auto-pairs = true
mouse = false
line-number = "relative"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["selections", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.lsp]
auto-signature-help = false

[keys.normal]
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.insert]
C-c = "normal_mode"

[keys.normal.space]
q = ":bc"
