theme = "zhxo-red"

[editor]
true-color = true
auto-pairs = true
mouse = false
line-number = "relative"
auto-format = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["selections", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[keys.normal]
C-right = "move_next_word_start"
C-left = "move_prev_word_end"

[keys.insert]
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
C-c = "normal_mode"
C-h = "move_char_left"
C-j = "move_visual_line_down"
C-k = "move_visual_line_up"
C-l = "move_char_right"
