theme = "zhxo-red"

[editor]
true-color = true
auto-pairs = true
mouse = false
line-number = "relative"
cursorline = true
bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "total-line-numbers"]
right = ["selections", "position"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.lsp]
auto-signature-help = false

# [editor.indent-guides]
# render = true
# character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
# skip-levels = 1

[keys.normal]
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.insert]
C-c = "normal_mode"

[keys.normal.space]
q = ":bc"
s = "select_all"
